import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  subsets: ["latin"],
});

export const metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${manrope.className} antialiased bg-base-300 text-base-content`}>
      <body>
        {children}
      </body>
    </html>
  );
}
